<a href="https://colab.research.google.com/github/piyushh044/cp_notes/blob/master/Copy_of_Stud_Que.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv("student_performance.csv")
df

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
0,1,18.5,95.6,3.8,97.9,A
1,2,14.0,80.0,2.5,83.9,B
2,3,19.5,86.3,5.3,100.0,A
3,4,25.7,70.2,7.0,100.0,A
4,5,13.4,81.9,6.9,92.0,A
...,...,...,...,...,...,...
563208,563209,8.0,84.9,6.7,80.9,B
563209,563210,26.5,95.1,4.7,100.0,A
563210,563211,16.3,91.4,7.2,88.5,A
563211,563212,18.6,79.8,7.0,100.0,A
563212,563213,21.8,74.1,NaN,NaN,NaN

### How many rows and columns are there in the dataset?

In [ ]:
df.shape

(563213, 6)

### Show the first 10 rows of the dataset.

In [ ]:
df.head(10)

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
0,1,18.5,95.6,3.8,97.9,A
1,2,14.0,80.0,2.5,83.9,B
2,3,19.5,86.3,5.3,100.0,A
3,4,25.7,70.2,7.0,100.0,A
4,5,13.4,81.9,6.9,92.0,A
5,6,13.4,65.1,5.0,97.5,A
6,7,26.1,81.8,5.9,100.0,A
7,8,20.4,100.0,4.0,96.1,A
8,9,11.7,100.0,8.2,69.8,C
9,10,18.8,67.6,6.0,80.3,B

### Show the last 10 rows of the dataset.

In [ ]:
df.tail(10)

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
563203,563204,15.3,91.8,7.8,68.6,C
563204,563205,10.3,86.7,3.5,70.2,B
563205,563206,5.4,92.6,5.0,45.2,D
563206,563207,16.4,77.4,7.5,100.0,A
563207,563208,16.7,83.4,8.5,100.0,A
563208,563209,8.0,84.9,6.7,80.9,B
563209,563210,26.5,95.1,4.7,100.0,A
563210,563211,16.3,91.4,7.2,88.5,A
563211,563212,18.6,79.8,7.0,100.0,A
563212,563213,21.8,74.1,NaN,NaN,NaN

### What are the column names in the dataset?

In [ ]:
df.columns

Index(['student_id', 'weekly_self_study_hours', 'attendance_percentage',
       'class_participation', 'total_score', 'grade'],
      dtype='object')

### What is the maximum value of weekly_self_study_hours?

In [ ]:
df['weekly_self_study_hours'].max()

40.0

### Which student studied the most hours in a week?

In [ ]:
df[df['weekly_self_study_hours'] == df['weekly_self_study_hours'].max()]

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
209,210,40.0,68.1,6.7,100.0,A
2895,2896,40.0,75.7,4.2,100.0,A
15843,15844,40.0,99.5,8.0,100.0,A
18851,18852,40.0,91.7,7.0,100.0,A
20126,20127,40.0,94.1,3.0,100.0,A
...,...,...,...,...,...,...
511604,511605,40.0,94.3,4.7,100.0,A
512025,512026,40.0,89.3,2.8,100.0,A
539838,539839,40.0,63.1,2.9,100.0,A
549006,549007,40.0,87.2,6.9,100.0,A
563050,563051,40.0,73.8,7.8,100.0,A

### Show the top 5 students by weekly_self_study_hours.

In [ ]:
df.sort_values('weekly_self_study_hours',ascending=False)

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
425630,425631,40.0,89.0,8.4,100.0,A
28552,28553,40.0,76.7,8.4,100.0,A
425349,425350,40.0,90.4,2.0,100.0,A
295058,295059,40.0,79.3,8.0,100.0,A
52813,52814,40.0,66.9,4.7,100.0,A
...,...,...,...,...,...,...
263420,263421,0.0,87.5,5.6,35.9,F
295024,295025,0.0,82.4,6.6,33.0,F
491944,491945,0.0,100.0,2.9,54.5,D
491928,491929,0.0,100.0,3.0,54.7,D
544314,544315,0.0,86.3,6.2,44.1,D

### Which student has the highest attendance percentage?

In [ ]:
std = df[df['attendance_percentage'] == df['attendance_percentage'].max()].count()
tot = df.shape[0]
percentage = (std*100)/tot
percentage

student_id                 6.795298
weekly_self_study_hours    6.795298
attendance_percentage      6.795298
class_participation        6.795298
total_score                6.795298
grade                      6.795298
dtype: float64

### Which student has the highest class participation?

In [ ]:
df[df['class_participation'] == df['class_participation'].max()]

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
137,138,12.7,78.3,10.0,78.7,B
148,149,18.7,92.8,10.0,100.0,A
159,160,19.6,78.5,10.0,93.2,A
221,222,1.9,78.8,10.0,46.4,D
228,229,10.0,65.7,10.0,69.5,C
...,...,...,...,...,...,...
563004,563005,29.1,76.3,10.0,100.0,A
563080,563081,12.8,67.9,10.0,78.4,B
563087,563088,9.9,94.1,10.0,60.0,C
563120,563121,10.6,97.9,10.0,82.8,B
563145,563146,13.5,82.9,10.0,96.7,A

### Create a new column score_level
"High" if total_score ≥ 90 , "Medium" if 70 ≤ total_score < 90, "Low" if total_score < 70

In [ ]:
def level(x):
  if x >= 90:
    return 'High'
  elif x>=70:
    return 'medium'
  else:
    return 'Low'

In [ ]:
df['scoring_level'] = df['total_score'].apply(level)

In [ ]:
df

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade,scoring_level
0,1,18.5,95.6,3.8,97.9,A,High
1,2,14.0,80.0,2.5,83.9,B,medium
2,3,19.5,86.3,5.3,100.0,A,High
3,4,25.7,70.2,7.0,100.0,A,High
4,5,13.4,81.9,6.9,92.0,A,High
...,...,...,...,...,...,...,...
563208,563209,8.0,84.9,6.7,80.9,B,medium
563209,563210,26.5,95.1,4.7,100.0,A,High
563210,563211,16.3,91.4,7.2,88.5,A,medium
563211,563212,18.6,79.8,7.0,100.0,A,High
563212,563213,21.8,74.1,NaN,NaN,NaN,Low

### Which student has the highest total_score?

### How many students scored exactly 100 in total_score?

### Make a new column for study efficiency = total_score ÷ weekly_self_study_hours.

### Create a new column study_category
"Light" if weekly_self_study_hours < 10,
"Moderate" if 10 ≤ hours ≤ 20,
"Heavy" if hours > 20